name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage
    - name: Test Cov 1
      run: |
        XCTEST_PATH="$(find . -name '*.xctest')"
        set -- $(xcrun llvm-cov report ${XCTEST_PATH}/Contents/MacOS/*PackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex='.build/|Tests/' | tail -1)
        echo "$4" > .build/debug/codecov/percentage.txt
        echo "PERCENTAGE=$4" >> $GITHUB_ENV
    - name: Test Cov 2
      uses: maxep/spm-lcov-action@0.3.1
    - name: Create COV Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_UPDATE }}
        gistID: ad941184ed256708952a2057fc5d7bb4
        filename: test.json
        label: Coverage
        message: ${{ env.PERCENTAGE }}
        color: success
