name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

jobs:
  build_macos:
    runs-on: macos-12
    strategy:
      matrix:
        xcode:
          - "14.2"
        commands:
          - test
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: System
      run: system_profiler $PHardwareDataType
    - name: Run
      run: make
    - name: Get Test Coverage
      run: |
        set -x
        set -- $(< percentage.txt)
        echo "PERCENTAGE=${1}" >> $GITHUB_ENV
    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_UPDATE }}
        gistID: ad941184ed256708952a2057fc5d7bb4
        filename: swift-math-parser-coverage.json
        label: Coverage
        message: ${{ env.PERCENTAGE }}
        color: success

  build_ubuntu:
    strategy:
      matrix:
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test

  build_windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - uses: MaxDesiatov/swift-windows-action@v1
        with:
          swift-version: "5.7"
